-- AssuredOpsSuite: Supabase Migration
-- Run this in the Supabase SQL Editor (Dashboard > SQL Editor > New Query)

-- ========== TABLES ==========

CREATE TABLE IF NOT EXISTS employees (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text,
  phone text,
  department text not null,
  position text not null,
  hire_date text not null,
  termination_date text,
  status text not null default 'active',
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS equipment_catalog (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  unit_cost numeric not null default 0,
  description text,
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS equipment_assignments (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  equipment_catalog_id bigint not null references equipment_catalog(id),
  serial_number text,
  assigned_date text not null,
  returned_date text,
  condition_on_return text,
  assigned_by text,
  department text not null,
  notes text,
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS kpis (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  target_value numeric,
  current_value numeric default 0,
  unit text,
  department text,
  period text,
  status text default 'on_track',
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS kpi_history (
  id bigint generated by default as identity primary key,
  kpi_id bigint not null references kpis(id),
  value numeric not null,
  recorded_date text not null default current_date::text,
  notes text
);

CREATE TABLE IF NOT EXISTS termination_bills (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  total_equipment_cost numeric not null default 0,
  items_returned integer default 0,
  items_not_returned integer default 0,
  amount_due numeric not null default 0,
  bill_date text default current_date::text,
  status text default 'pending',
  notes text,
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS programs (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  description text,
  manager_name text,
  manager_title text,
  status text default 'active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS program_documents (
  id bigint generated by default as identity primary key,
  program_id bigint not null references programs(id),
  title text not null,
  doc_type text not null,
  status text default 'draft',
  version text default '1.0',
  assigned_to text,
  due_date text,
  completed_date text,
  file_url text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS program_tasks (
  id bigint generated by default as identity primary key,
  program_id bigint not null references programs(id),
  title text not null,
  description text,
  priority text default 'medium',
  status text default 'todo',
  assigned_to text,
  due_date text,
  completed_date text,
  category text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS program_milestones (
  id bigint generated by default as identity primary key,
  program_id bigint not null references programs(id),
  title text not null,
  target_date text,
  completed_date text,
  status text default 'upcoming',
  notes text,
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS program_measures (
  id bigint generated by default as identity primary key,
  program_id bigint not null references programs(id),
  category text not null,
  name text not null,
  description text,
  baseline_requirements text,
  efficiency_requirements text,
  installation_standards text,
  is_emergency_only integer default 0,
  h_and_s_cap_exempt integer default 0,
  sort_order integer default 0,
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS measure_photo_requirements (
  id bigint generated by default as identity primary key,
  measure_id bigint not null references program_measures(id),
  photo_description text not null,
  timing text default 'both',
  required integer default 1,
  sort_order integer default 0
);

CREATE TABLE IF NOT EXISTS measure_paperwork_requirements (
  id bigint generated by default as identity primary key,
  measure_id bigint not null references program_measures(id),
  document_name text not null,
  description text,
  required integer default 1,
  sort_order integer default 0
);

CREATE TABLE IF NOT EXISTS program_process_steps (
  id bigint generated by default as identity primary key,
  program_id bigint not null references programs(id),
  phase text not null,
  step_number integer not null,
  title text not null,
  description text,
  required_certification text,
  required_forms text,
  timeline text,
  sort_order integer default 0
);

CREATE TABLE IF NOT EXISTS program_eligibility_rules (
  id bigint generated by default as identity primary key,
  program_id bigint not null references programs(id),
  rule_type text not null,
  title text not null,
  description text,
  sort_order integer default 0
);

CREATE TABLE IF NOT EXISTS program_deferral_rules (
  id bigint generated by default as identity primary key,
  program_id bigint not null references programs(id),
  condition_text text not null,
  sort_order integer default 0
);

CREATE TABLE IF NOT EXISTS program_jobs (
  id bigint generated by default as identity primary key,
  program_id bigint not null references programs(id),
  job_number text,
  customer_name text,
  address text,
  city text,
  zip text,
  utility text,
  status text default 'assessment_scheduled',
  phone text,
  email text,
  assessment_date text,
  assessment_data text,
  scope_data text,
  submission_date text,
  estimate_amount numeric,
  abc_install_date text,
  wall_injection_date text,
  patch_date text,
  hvac_tune_clean_date text,
  hvac_replacement_date text,
  install_date text,
  inspection_date text,
  needs_permit integer default 0,
  permit_status text default 'not_needed',
  permit_applied_date text,
  permit_received_date text,
  permit_number text,
  permit_jurisdiction text,
  permit_notes text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS job_measures (
  id bigint generated by default as identity primary key,
  job_id bigint not null references program_jobs(id),
  measure_id bigint not null references program_measures(id),
  status text default 'scoped',
  pre_condition text,
  post_condition text,
  notes text,
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS hvac_replacements (
  id bigint generated by default as identity primary key,
  job_id bigint not null references program_jobs(id),
  equipment_type text not null,
  existing_make text,
  existing_model text,
  existing_condition text,
  existing_efficiency text,
  existing_age text,
  decision_tree_result text,
  tech_report_sent integer default 0,
  tech_report_date text,
  tech_report_sent_to text,
  approval_status text default 'pending',
  approval_date text,
  manual_j_complete integer default 0,
  manual_j_btu text,
  new_make text,
  new_model text,
  new_efficiency text,
  new_size text,
  install_date text,
  billing_amount numeric,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS change_orders (
  id bigint generated by default as identity primary key,
  job_id bigint not null references program_jobs(id),
  requested_by text not null,
  request_type text not null default 'scope_change',
  description text not null,
  measures_to_add text,
  measures_to_remove text,
  reason text,
  status text default 'pending',
  reviewed_by text,
  review_date text,
  review_notes text,
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS job_photos (
  id bigint generated by default as identity primary key,
  job_id bigint not null references program_jobs(id),
  uploaded_by text not null,
  role text not null,
  phase text not null,
  measure_name text,
  house_side text,
  description text not null,
  photo_ref text,
  photo_data text,
  file_name text,
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS job_checklist_items (
  id bigint generated by default as identity primary key,
  job_id bigint not null references program_jobs(id),
  item_type text not null,
  description text not null,
  measure_id bigint references program_measures(id),
  completed integer default 0,
  completed_date text,
  completed_by text,
  notes text
);

-- ========== ROW LEVEL SECURITY ==========
-- Permissive policies for all tables (internal company tool)
-- Tighten these if you add authentication later

DO $$
DECLARE
  t text;
BEGIN
  FOR t IN
    SELECT unnest(ARRAY[
      'employees', 'equipment_catalog', 'equipment_assignments',
      'kpis', 'kpi_history', 'termination_bills',
      'programs', 'program_documents', 'program_tasks', 'program_milestones',
      'program_measures', 'measure_photo_requirements', 'measure_paperwork_requirements',
      'program_process_steps', 'program_eligibility_rules', 'program_deferral_rules',
      'program_jobs', 'job_measures', 'hvac_replacements', 'change_orders',
      'job_photos', 'job_checklist_items'
    ])
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY "Allow all select" ON %I FOR SELECT USING (true)', t);
    EXECUTE format('CREATE POLICY "Allow all insert" ON %I FOR INSERT WITH CHECK (true)', t);
    EXECUTE format('CREATE POLICY "Allow all update" ON %I FOR UPDATE USING (true) WITH CHECK (true)', t);
    EXECUTE format('CREATE POLICY "Allow all delete" ON %I FOR DELETE USING (true)', t);
  END LOOP;
END $$;
